version: "3.8"

name: messenger
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sunday
      POSTGRES_PASSWORD: sunday
      POSTGRES_DB: messenger-db
    ports:
      - "7777:5432"
    volumes:
      - ./data/postgres:/var/lib/postgres

volumes:
  postgres_data:
